### ISSUE TITLE
Add support for script tag usage in browsers - rename index.cjs

### ISSUE THREAD

**Issue by dotnetCarpenter** [fluture-js/fluture-sanctuary-types#73]
First off, thank you for creating these typings!

I'm completely new to Sancturary and Fluture and already I feel productive with Sanctuary's awesome type checking.

But after a lot of initial head scratching, since my requirements are bit odd (old).

I maintain a website that was build 6 years ago with jQuery, underscore.js and express, [ejs](https://ejs.co) on the server.

We do not have a built step for javascript (we do for CSS) and I had to figure out how to combine Sancturary + Fluture + jQuery in the browser. Luckily we only support ES2015, so modules are supported.

I came up with the following as a proof of concept:

```HTML
<p id="output">Loading...</p>

<script>
	'use strict'
	const process = {}
	process.env = {}
	process.env.NODE_ENV = 'dev'
</script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/gh/sanctuary-js/sanctuary@3.1.0/dist/bundle.js"></script>
<script type="module" src="js/app.js"></script>
```

_js/app.js_
```js
import { env as flutureEnv } from './fluture-sanctuary-types@7.0.1.js'
import { Future, fork } from 'https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js'


/** @type {import('sanctuary')} */
const S = window.sanctuary.create({ checkTypes: true, env: window.sanctuary.env.concat(flutureEnv) })

// getJSON :: String -> {} -> Task Error JN
const getJSON = S.curry2((url, params) => Future((reject, result) => {
	$.getJSON(url, params, result).fail(reject)

	// Here is how we handle cancellation. This signal is received when nobody
	// is interested in the answer any more.
	return function onCancel () {
		// Clearing the timeout releases the resources we were holding.
		console.log('Future was cancelled')
	}
}))

const display = S.pipe([
	S.prop('publishableKey'),
	key => $('#output').text(key)
])

fork (console.error) (display)
	(getJSON('/setup') ({}))
```

`'./fluture-sanctuary-types@7.0.1.js'` is my edited version of the current typings, since I can not use the implementation as it is.

The following changes was needed before I could get it to work:
```js
const $D = window.sanctuaryDef
const type = window.sanctuaryTypeIdentifiers
import {
  Future,
  isFuture,
  extractLeft,
  extractRight,
  Par,
  seq
} from 'https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js';
```
Contrast that with what is provided by [fluture-sanctuary-types](https://github.com/fluture-js/fluture-sanctuary-types/) today:
```js
import $ from 'sanctuary-def';
import type from 'sanctuary-type-identifiers';
import {
  Future,
  isFuture,
  extractLeft,
  extractRight,
  Par,
  seq
} from 'fluture/index.js';
```

Both _app.js_ and _fluture-sanctuary-types@7.0.1.js_ imports "https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js" but it is only loaded by the browser once.
The `process.env.NODE_ENV` stuff is to turn Sanctuary type checking on/off.

Notice that `$` had to be renamed to `$D` to not conflict with jQuery.

That was a lot of pretext.. What I wanted to ask is, is it possible to get a built hosted on jsDelivr that assumes Sancturary is global and imports Fluture from a CDN (preferably jsDelivr too)?
I'm not sure if depending on jsDelivr is the right path for everyone who needs to run Sanctuary + Fluture directly in the browser but it is an idea.

_By the way, `fluture-sanctuary-types` works great with Fluture 14 in my very limited test. Currently npm will loudly protest if you try to use Fluture 14 because of [the peer dependency semver requirement](https://github.com/fluture-js/fluture-sanctuary-types/blob/master/package.json#L49)._

**Comment by dotnetCarpenter** [comment]
Actually, defining which version of Fluture to use directly might be an issue as well.

... I now see that there is https://cdn.jsdelivr.net/npm/fluture-sanctuary-types@7.0.1/index.cjs but that can not load in the browser because jsDelivr sets `application/node` as MIME-type.

>Failed to load module script: The server responded with a non-JavaScript MIME type of "application/node". Strict MIME type checking is enforced for module scripts per HTML spec.

How about renaming the file to something else?

**Comment by dotnetCarpenter** [comment]
I just tried to include _index.cjs_ as a regular script but got the following error in Opera:

> Refused to execute script from 'https://cdn.jsdelivr.net/npm/fluture-sanctuary-types@7.0.1/index.cjs' because its MIME type ('application/node') is not executable, and strict MIME type checking is enabled.

I also edited _app.js_ to:

```js
import { Future, fork } from 'https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js'

const flutureEnv = window.flutureSanctuaryTypes.env

/** @type {import('sanctuary')} */
const S = window.sanctuary.create({ checkTypes: true, env: window.sanctuary.env.concat(flutureEnv) })
```

Which I assume will work if _index.cjs_ would load.

**Comment by Avaq** [comment]
Hi, thank you for reporting on the issues you're encountering!

> We do not have a built step for javascript (we do for CSS) and I had to figure out how to combine Sancturary + Fluture + jQuery in the browser. Luckily we only support ES2015, so modules are supported. [...] What I wanted to ask is, is it possible to get a built hosted on jsDelivr that assumes Sancturary is global and imports Fluture from a CDN (preferably jsDelivr too)?

There are a few approaches I can think of that may work for you:

1. Install packages using [snowpack](https://www.snowpack.dev/concepts/how-snowpack-works#using-npm-dependencies), so that they are automatically rewritten to load their dependencies from a browser-friendly path.
2. Load the modules from a pre-packaging CDN such as [Skypack](https://www.skypack.dev/) or [jspm](https://jspm.org/), which does the same in essence as option 1, but "as a service" at the CDN level.

> I now see that there is https://cdn.jsdelivr.net/npm/fluture-sanctuary-types@7.0.1/index.cjs but that can not load in the browser

Ah, you're attempting to use this because it's a Universal Module, so it uses `global.sanctuaryDef` and such when `module` and `define` are both `undefined`.

This looks like an inconsistency on my part. I should not use the `.cjs` extension for files that are not strictly CommonJS-only. Although my intention was for this file to be a CommonJS build for older Node, I must say that it does come close to what you need. So a third solution might be for me to include a universal module in `dist` with a `.js` extension for script usage (similar to what Fluture does) and change the `index.cjs` file to be strictly commonjs.

Before I rush off to do this, however, perhaps you could have a look at one of the two options I gave earlier. Would any of these work for you?

----

> By the way, `fluture-sanctuary-types` works great with Fluture 14

Right. Fluture 14 was just released and I haven't updated fluture-sanctuary-types' version range yet. It should be completely compatible. I will update the package.json accordingly.

**Comment by jimaek** [comment]
Maybe this would help https://www.jsdelivr.com/esm ?

**Comment by Avaq** [comment]
Ah, I didn't know about that @jimaek. That seems like the ideal option thus far. I think it's like option 2 but hosted by jsDelivr. :)

**Comment by dotnetCarpenter** [comment]
@Avaq thank you for your suggestions!

I'm trying to wrap my head around the jsDelivr esm solution.

So I would import like so:
```js
import { env as flutureEnv } from 'https://cdn.jsdelivr.net/npm/fluture-sanctuary-types/+esm'
```
That throws:
>Uncaught SyntaxError: The requested module '/npm/sanctuary-show@2.0.0/+esm' does not provide an export named 'default'

Am I doing this right?

On the surface your third suggestion seems to be the easiest for me to work with currently. But that is mostly because I do not know snowpack at all and I rather not use another CDN service, since we already use jsDelivr on our website.

> So a third solution might be for me to include a universal module in dist with a .js extension for script usage (similar to what Fluture does) and change the index.cjs file to be strictly commonjs.

**Comment by Avaq** [comment]
> Am I doing this right?

Yes, you are, as far as I can tell.

> That throws [an] Uncaught SyntaxError

It seems that jsdelivr does not convert non-esm modules to esm, so the file at https://cdn.jsdelivr.net/npm/sanctuary-show@2.0.0/+esm does not contain any exports. The reason this *does* work in Node is because Node has [built-in CommonJS compatbility when using `import`](https://nodejs.org/dist/latest/docs/api/esm.html#esm_interoperability_with_commonjs).

Both Skypack and jspm do convert commonjs modules to esm:

- Skypack: <code>import from '<a href="https://cdn.skypack.dev/fluture-sanctuary-types">https://cdn.skypack.dev/fluture-sanctuary-types</a>'</code> (see [converted sanctuary-show](https://cdn.skypack.dev/-/sanctuary-show@v2.0.0-CslS6PHedkWAAh8kuA9z/dist=es2020,mode=imports/optimized/sanctuary-show.js))
- jspm: <code>import from '<a href="https://jspm.dev/fluture-sanctuary-types">https://jspm.dev/fluture-sanctuary-types</a>'</code> (see [converted sanctuary-show](https://jspm.dev/npm:sanctuary-show@2.0.0!cjs))

I imagine that jsdelivr is working on a similar solution (they mention that they're in beta).

That said, I'll also look into pushing a regular script to a /dist folder for jsdelivr to pick up on. That would then also help users who have to support older browsers.

**Comment by dotnetCarpenter** [comment]
Can't believe https://cdn.skypack.dev/-/sanctuary-show@v2.0.0-CslS6PHedkWAAh8kuA9z/dist=es2020,mode=imports/optimized/sanctuary-show.js and https://jspm.dev/npm:sanctuary-show@2.0.0!cjs is the same code. At a glance it looks so different.

> I'll also look into pushing a regular script to a /dist folder for jsdelivr to pick up on. That would then also help users who have to support older browsers.

Thank you, that would be awesome! If you plan to have that in the next release, I can use my home backed solution for 7.0.1 until then.  And then make the changes accordingly. I will watch this repo :)
